<section class="h-100">
    <div class="container h-100">
        <div class="row justify-content-md-center align-items-center h-100">
            <div class="card-wrapper">
                <div class="brand">
                    <img src="/images/logo.png">
                </div>
                <div class="card fat">
                    <div class="card-body">
                        <h4 class="card-title">Esqueci minha senha</h4>
                        <form method="POST" action="/login/reset">

                            <div class="form-group">
                                <label for="email">E-Mail</label>
                                <input id="email" type="email" class="form-control" name="email" value="" required autofocus>
                                <div class="form-text text-muted">
                                    "Resetar Senha" Enviaremos um link para seu email.
                                </div>
                            </div>

                            <div class="form-group no-margin">
                                <button type="submit" class="btn btn-primary btn-block">
                                    Resetar Senha
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="footer">
                    Copyright &copy; Your Company 2017
                </div>
            </div>
        </div>
    </div>
</section>
</body>
</html>