<section class="my-login-page">
    <div class="container h-100">
        <div class="row justify-content-md-center h-100">
            <div class="card-wrapper">
                <div class="brand">
                    <img src="images/logo.png">
                </div>
                <div class="card fat">
                    <div class="card-body">
                        <h4 class="card-title">Login</h4>
                        <form method="POST" action="login/validator">

                            <div class="form-group">
                                <label for="email">E-Mail</label>

                                <input id="email" type="email" class="form-control" name="email" value="" required autofocus>
                            </div>

                            <div class="form-group">
                                <label for="password">Senha</label>
                                <input id="password" type="password" class="form-control" name="password" required data-eye>
                            </div>

                            <div class="form-group">
                                <label>
                                    <a href="login/forgot" class="float-left">
                                        Esqueci minha senha.
                                    </a>
                                </label>
                            </div>

                            <div class="form-group no-margin">
                                <button type="submit" class="btn btn-primary btn-block">
                                    Login
                                </button>
                            </div>
                            <div class="margin-top20 text-center">
                                Não tem conta? <a href="login/register">Criar nova conta</a>
                            </div>

                        </form>
                    </div>
                </div>
                <div class="footer">
                    Copyright &copy; Your Company 2018
                </div>
            </div>
        </div>
    </div>
</section>
</div>
</html>