<?php $this->partials("navbar")?>


<br><br>
<h1>Professores</h1>

<table class="table table-striped table-hover">
    <thead>
    <tr>
        <th>Nome</th>
        <th>Email</th>
        <th>Telefone</th>
        <th>Cidade</th>
    </tr>
    </thead>

    <tbody>
    <tr>
        <td>Alessandro</td>
        <td>eu@alessandrofeitoza.eu</td>
        <td>(85) 9 8674-0502</td>
        <td>Fortaleza</td>
    </tr>
    <tr>
        <td>Alessandro</td>
        <td>eu@alessandrofeitoza.eu</td>
        <td>(85) 9 8674-0502</td>
        <td>Fortaleza</td>
    </tr>
    <tr>
        <td>Alessandro</td>
        <td>eu@alessandrofeitoza.eu</td>
        <td>(85) 9 8674-0502</td>
        <td>Fortaleza</td>
    </tr>
    <tr>
        <td>Alessandro</td>
        <td>eu@alessandrofeitoza.eu</td>
        <td>(85) 9 8674-0502</td>
        <td>Fortaleza</td>
    </tr>
    <tr>
        <td>Alessandro</td>
        <td>eu@alessandrofeitoza.eu</td>
        <td>(85) 9 8674-0502</td>
        <td>Fortaleza</td>
    </tr>
    <tr>
        <td>Alessandro</td>
        <td>eu@alessandrofeitoza.eu</td>
        <td>(85) 9 8674-0502</td>
        <td>Fortaleza</td>
    </tr>
    <tr>
        <td>Alessandro</td>
        <td>eu@alessandrofeitoza.eu</td>
        <td>(85) 9 8674-0502</td>
        <td>Fortaleza</td>
    </tr>
    <tr>
        <td>Alessandro</td>
        <td>eu@alessandrofeitoza.eu</td>
        <td>(85) 9 8674-0502</td>
        <td>Fortaleza</td>
    </tr>
    </tbody>
</table>

<div class="text-right">
    <a class="btn btn-primary" href="/professor/novo">
        Novo Professor
    </a>
</div>
<?php $this->partials("footer")?>