<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title></title>
    <link rel="stylesheet" href="App/public/assets/bootstrap/css/bootstrap.min.css">

</head>
<body class="container">
        <?php echo $this->navbar()?>
        <?php echo $this->content()?>
        <?php echo $this->footer()?>
</body>
</html>
<script src="App/public/assets/jquery/jquery-3.3.1.min.js"></script>
<script src="App/public/assets/bootstrap/js/bootstrap.bundle.js"></script>
<script src="App/public/assets/bootstrap/js/bootstrap.js"></script>
